#Create User
INSERT INTO `users` (`email`, `username`, `password`, `first_name`, `last_name`, `city`, `state`) VALUES
('kennith.mayo@email.com', 'kennith.mayo@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Kennith', 'Mayo', 'San Antonio', 'TX'),
('jerome.miles@email.com', 'jerome.miles@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jerome', 'Miles', 'San Antonio', 'TX'),
('beth.ellis@email.com', 'beth.ellis@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Beth', 'Ellis', 'San Antonio', 'TX'),
('lucio.sherman@email.com', 'lucio.sherman@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Lucio', 'Sherman', 'San Antonio', 'TX'),
('florencio.davila@email.com', 'florencio.davila@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Florencio', 'Davila', 'San Antonio', 'TX'),
('terry.hansen@email.com', 'terry.hansen@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Terry', 'Hansen', 'San Antonio', 'TX'),
('zachariah.casey@email.com', 'zachariah.casey@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Zachariah', 'Casey', 'San Antonio', 'TX'),
('cory.thompson@email.com', 'cory.thompson@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Cory', 'Thompson', 'San Antonio', 'TX'),
('alfonso.long@email.com', 'alfonso.long@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Alfonso', 'Long', 'San Antonio', 'TX'),
('anibal.spence@email.com', 'anibal.spence@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Anibal', 'Spence', 'San Antonio', 'TX'),
('oren.kim@email.com', 'oren.kim@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Oren', 'Kim', 'San Antonio', 'TX'),
('kristie.boyd@email.com', 'kristie.boyd@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Kristie', 'Boyd', 'San Antonio', 'TX'),
('frederic.rubio@email.com', 'frederic.rubio@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Frederic', 'Rubio', 'San Antonio', 'TX'),
('marty.stafford@email.com', 'marty.stafford@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Marty', 'Stafford', 'San Antonio', 'TX'),
('roger.merritt@email.com', 'roger.merritt@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Roger', 'Merritt', 'San Antonio', 'TX'),
('bryant.wyatt@email.com', 'bryant.wyatt@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Bryant', 'Wyatt', 'San Antonio', 'TX'),
('john.rasmussen@email.com', 'john.rasmussen@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'John', 'Rasmussen', 'San Antonio', 'TX'),
('rufus.gates@email.com', 'rufus.gates@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Rufus', 'Gates', 'San Antonio', 'TX'),
('vicente.lozano@email.com', 'vicente.lozano@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Vicente', 'Lozano', 'San Antonio', 'TX'),
('brandie.navarro@email.com', 'brandie.navarro@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Brandie', 'Navarro', 'San Antonio', 'TX'),
('heather.dickson@email.com', 'heather.dickson@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Heather', 'Dickson', 'San Antonio', 'TX'),
('dale.jarvis@email.com', 'dale.jarvis@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Dale', 'Jarvis', 'San Antonio', 'TX'),
('lelia.hines@email.com', 'lelia.hines@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Lelia', 'Hines', 'San Antonio', 'TX'),
('alexis.kaufman@email.com', 'alexis.kaufman@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Alexis', 'Kaufman', 'San Antonio', 'TX'),
('lakeisha.contreras@email.com', 'lakeisha.contreras@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Lakeisha', 'Contreras', 'San Antonio', 'TX'),
('britt.hartman@email.com', 'britt.hartman@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Britt', 'Hartman', 'San Antonio', 'TX'),
('sandy.ayala@email.com', 'sandy.ayala@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Sandy', 'Ayala', 'San Antonio', 'TX'),
('priscilla.hahn@email.com', 'priscilla.hahn@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Priscilla', 'Hahn', 'San Antonio', 'TX'),
('whitney.huang@email.com', 'whitney.huang@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Whitney', 'Huang', 'San Antonio', 'TX'),
('long.blake@email.com', 'long.blake@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Long', 'Blake', 'San Antonio', 'TX'),
('herschel.chapman@email.com', 'herschel.chapman@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Herschel', 'Chapman', 'San Antonio', 'TX'),
('hal.kane@email.com', 'hal.kane@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Hal', 'Kane', 'San Antonio', 'TX'),
('jeanne.townsend@email.com', 'jeanne.townsend@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jeanne', 'Townsend', 'San Antonio', 'TX'),
('spencer.daniels@email.com', 'spencer.daniels@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Spencer', 'Daniels', 'San Antonio', 'TX'),
('clair.rogers@email.com', 'clair.rogers@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Clair', 'Rogers', 'San Antonio', 'TX'),
('chauncey.duke@email.com', 'chauncey.duke@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Chauncey', 'Duke', 'San Antonio', 'TX'),
('brady.landry@email.com', 'brady.landry@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Brady', 'Landry', 'San Antonio', 'TX'),
('arlene.drake@email.com', 'arlene.drake@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Arlene', 'Drake', 'San Antonio', 'TX'),
('buck.ingram@email.com', 'buck.ingram@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Buck', 'Ingram', 'San Antonio', 'TX'),
('dane.woods@email.com', 'dane.woods@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Dane', 'Woods', 'San Antonio', 'TX'),
('gilberto.khan@email.com', 'gilberto.khan@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Gilberto', 'Khan', 'San Antonio', 'TX'),
('annabelle.bullock@email.com', 'annabelle.bullock@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Annabelle', 'Bullock', 'San Antonio', 'TX'),
('rosendo.benitez@email.com', 'rosendo.benitez@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Rosendo', 'Benitez', 'San Antonio', 'TX'),
('luke.murray@email.com', 'luke.murray@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Luke', 'Murray', 'San Antonio', 'TX'),
('elsie.may@email.com', 'elsie.may@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Elsie', 'May', 'San Antonio', 'TX'),
('odell.gamble@email.com', 'odell.gamble@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Odell', 'Gamble', 'San Antonio', 'TX'),
('laverne.williams@email.com', 'laverne.williams@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Laverne', 'Williams', 'San Antonio', 'TX'),
('flora.tanner@email.com', 'flora.tanner@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Flora', 'Tanner', 'San Antonio', 'TX'),
('val.jacobs@email.com', 'val.jacobs@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Val', 'Jacobs', 'San Antonio', 'TX'),
('jewel.fowler@email.com', 'jewel.fowler@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jewel', 'Fowler', 'San Antonio', 'TX'),
('esteban.thomas@email.com', 'esteban.thomas@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Esteban', 'Thomas', 'San Antonio', 'TX'),
('erna.chang@email.com', 'erna.chang@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Erna', 'Chang', 'San Antonio', 'TX'),
('grover.freeman@email.com', 'grover.freeman@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Grover', 'Freeman', 'San Antonio', 'TX'),
('rich.sheppard@email.com', 'rich.sheppard@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Rich', 'Sheppard', 'San Antonio', 'TX'),
('connie.grant@email.com', 'connie.grant@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Connie', 'Grant', 'San Antonio', 'TX'),
('angeline.waller@email.com', 'angeline.waller@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Angeline', 'Waller', 'San Antonio', 'TX'),
('lina.terrell@email.com', 'lina.terrell@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Lina', 'Terrell', 'San Antonio', 'TX'),
('pablo.kerr@email.com', 'pablo.kerr@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Pablo', 'Kerr', 'San Antonio', 'TX'),
('chad.palmer@email.com', 'chad.palmer@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Chad', 'Palmer', 'San Antonio', 'TX'),
('ahmed.zuniga@email.com', 'ahmed.zuniga@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Ahmed', 'Zuniga', 'San Antonio', 'TX'),
('jo.peck@email.com', 'jo.peck@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jo', 'Peck', 'San Antonio', 'TX'),
('cedric.jones@email.com', 'cedric.jones@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Cedric', 'Jones', 'San Antonio', 'TX'),
('henry.brun@email.com', 'henry.brun@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Henry', 'Brun', 'San Antonio', 'TX');

select id, username from users;

#Assign User Group 1-Admin, 2-Customer, 3-Vendor
INSERT INTO `user_groups` (`user_id`, `group_id`) VALUES
(90, 3),
(91, 3),
(92, 3),
(93, 3),
(94, 3),
(95, 3),
(96, 3),
(97, 3),
(98, 3),
(99, 3),
(100, 3),
(101, 3),
(102, 3),
(103, 3),
(104, 3),
(105, 3),
(106, 3),
(107, 3),
(108, 3),
(109, 3),
(110, 3),
(111, 3),
(112, 3),
(113, 3),
(114, 3),
(115, 3),
(116, 3),
(117, 3),
(118, 3),
(119, 3),
(120, 3),
(121, 3),
(122, 3),
(123, 3),
(124, 3),
(125, 3),
(126, 3),
(127, 3),
(128, 3),
(129, 3),
(130, 3),
(131, 3),
(132, 3),
(133, 3),
(134, 3),
(135, 3),
(136, 3),
(137, 3),
(138, 3),
(139, 3),
(140, 3),
(141, 3),
(142, 3),
(143, 3),
(144, 3),
(145, 3),
(146, 3),
(147, 3),
(148, 3),
(149, 3),
(150, 3),
(151, 3),
(152, 3);

#Create Vendor
INSERT INTO `vendors` (`user_id`, `business_name`, `category_id`, `about`) VALUES
(90,'Mokara Hotel and Spa',1,'Mokara Hotel & Spa has a long-standing history of excellence. As the only four-star hotel in San Antonio, Mokara Hotel & Spa is the first choice for sophisticated travelers. Experience Mokara Hotel & Spa, a relaxing retreat on San Antonio’s world-famous River Walk. Just steps from all the action yet worlds away, this inviting oasis has all the best creature comforts easily at hand, including luxurious accommodations, first-class amenities, fine dining and a full-service spa.'),
(91,'Crown Ridge Banquet Hall',1,'Crown Ridge Event Center is ideally located in the Hill Country surroundings of San Antonio. The exquisite banquet hall is the perfect location for your wedding celebration! Crown Ridge provides you with several options for your special day. You can opt to host your reception in either the Columbus Room or the Christopher Room. You also have the option of renting and using the entire hall. You can host all the festivities of your special day on site—ceremony, cocktail hour, and reception!'),
(92,'JW Marriott San Antonio Hill Country Resort & Spa',1,'Nestled amid 600 acres of oak-covered hills, JW Marriott San Antonio Hill Country Resort & Spa is a luxury haven within a stunning landscape. Explore the area\'s most popular attractions, including wineries, SeaWorld, Shops at La Cantera, Natural Bridge Caverns and Six Flags Fiesta Texas. Retreat to our hotel for the thrilling River Bluff Water Experience, a nine-acre water park featuring a 1,100-foot lazy river. Celebrate and succeed in 268,000 square feet of sophisticated event space, featuring outdoor pavilions and elegant ballrooms. After a full day of business or sightseeing in San Antonio, TX, savor delectable fare at one of our six resort restaurants, or rejuvenate your wellbeing at our luxury spa. Find your respite in upscale accommodations with expansive floor plans, plush furnishings, premium amenities and breathtaking views of the Texas Hill Country. An inspiring destination with something for everyone, our resort offers quiet luxury in the beautiful Texas Hill Country.'),
(93,'The Gardens at West Green',1,'The Gardens at West Green is San Antonio’s most unique Small Wedding Venue. We specialize in outdoor garden weddings for the couple who is looking for an intimate ceremony and reception venue at an affordable price. The Gardens at West Green offers an Intimate Garden Wedding at an Affordable Price. It is the first in San Antonio to offer an alternative to the traditional event venue. The peaceful and serene locale provides a beautiful backdrop to your wedding day. Surrounded by centurion oaks and natural vegetation it\'s the perfect solution to a beautiful wedding. Peak seasons are in Spring, Summer, and Fall. Located on Two and a half acres, The Gardens at West Green makes the perfect location for your upcoming Wedding or Gathering. There are so many ways to personalize your special day so that you can create original and holistic themes that bring beauty and joy to even the smallest event. Contact us for availability and additional services.'),
(94,'Ivy Hall Events',1,'The Gardens at West Green is San Antonio’s most unique Small Wedding Venue. We specialize in outdoor garden weddings for the couple who is looking for an intimate ceremony and reception venue at an affordable price. The Gardens at West Green offers an Intimate Garden Wedding at an Affordable Price. It is the first in San Antonio to offer an alternative to the traditional event venue. The peaceful and serene locale provides a beautiful backdrop to your wedding day. Surrounded by centurion oaks and natural vegetation it\'s the perfect solution to a beautiful wedding. Peak seasons are in Spring, Summer, and Fall. Located on Two and a half acres, The Gardens at West Green makes the perfect location for your upcoming Wedding or Gathering. There are so many ways to personalize your special day so that you can create original and holistic themes that bring beauty and joy to even the smallest event. Contact us for availability and additional services.'),
(95,'Rancho La Mission',1,'Welcome to Rancho la Mission. We have two venues to choose from – the outdoor venue and the indoor venue, aka "The Barn”. To start the outdoor venue gives you an open-air feel with a rustic winter wonderland filled with lots of tree lights. Plenty of outdoor space for any outdoor event. If you prefer a indoor venue, than The Barn is a perfect, country theme for your ceremony and reception or any event. We are honored to host your event and look forward to start planning your BIG day!'),
(96,'Devils River Distillery',1,'Devils River Distillery, situated in San Antonio, TX, offers event space for weddings and other special celebrations. This venue is located only a short distance from the city’s historic River Walk, providing a convenient setting that also allows for beautiful photos. Whiskey enthusiasts will appreciate that the distillery is home to Devils River Whiskey, which was founded in 2016. Whether your special day calls for an intimate gathering of 50 or a grand gala with up to 200 guests, this venue’s happy to assist. The Venue at Devils River Distillery features a luxurious bridal suite on the level of the Grand Mezzanine. The Tasting Room/Main Floor is ideal for wedding ceremonies, boasting an antique bar and copper stills that help to create a unique atmosphere. Finally, The Speakeasy, located on the downstairs level, is perfect for hosting unforgettable receptions. It includes glowing wall sconces and an ambiance that’s reminiscent of speakeasies from the Prohibition era.'),
(97,'Magnolia Halle',1,'We are San Antonio\'s full service event venue center. Located just off of I-10 and Huebner Rd, you won\'t have to travel far to find the perfect location for any occasion​. As a family owned and operated business we love being able to help created memories that people can remember for a lifetime. HILL COUNTRY FEEL. EFFORTLESS EXPERIENCE.'),
(98,'Mother Teresa and Feed Back Catering',1,'Mother Teresa is a New Building Venue with all the regulations, nice Food services and Bar services BYOB, Capacity of 350 guests , Free parking Lot located at 375 Fairview St. Feed Back catering on business Since 1996 with another 25 Locations all over San Antonio , with the best reputation on Good Food - Services and Excellent prices Please visit us at (personal information protected by Wedding Wise)'),
(99,'First Delight Photography',2,'Cassia and Aaron are San Antonio-based wedding photographers. From intimate backyards to large destination weddings, we want to document one of the most impactful moments of your life. With a passion for people, along with our contemporary, photo-journalistic and candid style, we will capture memories in a way that you can enjoy forever. Cassia & her husband Aaron are the photographers behind First Delight Photography. She has been part of the wedding scene since 2013.\n\nWe are in love so we cherish our love story. We know each story is unique, beautiful and has all the quirks. Hearing your story will give us insight on how to capture a your day as it unfolds and all the people and moments that make your day, yours.'),
(100,'John G Photography LLC',2,'John G Photography LLC is a wedding photography business based in San Antonio, Texas. Owner John Gutierrez is an award-winning storyteller who enjoys a good love story! His style of photography brings out the best of your wedding day by capturing candid, authentic moments of pure joy to create a timeless, visual timeline. Couples will be able to reminisce back on their special day, reliving every emotion they felt in the moment, and thus bringing them even closer in love for years to come when looking back on their photos.'),
(101,'Ashley & Tyler Photography',2,''),
(102,'Philip Thomas Photography',2,'A Brit from just south of London in England, I have lived in Texas since 2006, when I moved to marry my best friend. Before moving to America, I was a newspaper photographer covering local stories and sports, managed a portrait studio, and traveled the world. A lifelong photographer, I\'ve spent an unhealthy amount of time in darkrooms developing rolls of film and learning from amazing mentors.'),
(103,'David Pezzat Photographers',2,'David Pezzat Photographers is a San Antonio-based business that specializes in local as well as destination weddings. David Pezzat is an award-winning photographer who started practicing photography when he was just 16. His exclusive work has been featured in many well-known publications, such as Project Wedding, Maxwell Brides Magazine, Grace Ormonde Wedding Style Magazine, and The Valley Wedding Pages. Hire David and let him create artistic and unique photographs that can reflect connection, emotions, and feelings.'),
(104,'Idea House Media',2,'Thanks for considering us, your time just looking into our work is important to us. Our team has bee capturing memories together for more than for seven years. My wife owns a bakery that does wedding cakes and we just love everything wedding. We are also very helpful people who would love to answer your wedding questions. \n\nOur reputation is founded upon our creative perspective, our "WOW” factor, and our dedication to never miss a moment. We don\'t just make wedding videos, we produce "Wedding Films" where we tell your love story though live audio and footage from your special day. We stand apart from typical wedding services by not just giving our customers the basics but something different and particular to each couple.'),
(105,'Aliyah Vargas Photography',2,'Hey y\'all! Welcome and congrats on your engagement! I\'m Aliyah, a photographer based in Texas, but available anywhere. If I\'m not out shooting, you can find me listening to crime podcasts and chasing my two toddlers around. I\'m a hopeless romantic and I\'ve probably binged watched every cheesy Hallmark movie. I celebrate ALL love! I strive to make my couples feel comfortable and confident no matter what. I love to laugh and have fun so let\'s get this party started! \n\nMy goal is for you to enjoy your wedding day and be present! I will be there to photograph, assist, and have Kleenex handy when needed. Need someone to hold your dress while you pee? Need to vent? Your hair is in the way? I got you. I am your biggest hype man and the best third wheel.'),
(106,'Evelyn Photography',2,'Evelyn here, I\'m the one behind the camera, I could spend the whole day talking about myself, but here are a few things you should know about me. As a single mother of two girls, I am the most dedicated and passionate person when it comes to being your photographer. Spanish is my first language since I\'m 100% Mexican! While I was born and raised in a small border town called Piedras Negras, my heart belongs to San Antonio. I have lived here for 16 years, so I am practically half and half. \n\nPhotography is not just a hobby for me. It is a way of expression, passion, and art. Every photograph has a story to tell, and there is no better way to remember you or your loved ones than through a photograph. So don\'t hesitate to chat, tell me all about your special moment, and I\'ll be there!'),
(107,'Greg Reese Events',2,'For over two decade Greg Reese designed events for others like Events Destination Weddings Galas. His passion and desire to set out on his own and to create his own identity. In other words, he had a vision of creating a company unlike any other in South Texas. He knew that with his creative ideas, eye for luxury and knowledge of the industry, there would be tremendous opportunities for his new startup. \n\nBecause Greg Reese Events team sets us apart. We’re a group of professionals that share a passion for what we do, as well as a commitment to make your event everything you’ve imagined and beyond. Today Greg Reese plans and designs elegant and spectacular weddings, corporate and destination weddings, We take great pride in creating one-of-a-kind events that truly represent the clients’ style and personality. Greg creates more than just a party, we create an event that tells the complete story of the couple.'),
(108,'Enchanted Florists',3,'I’m Shayna and my sister Shelby and I want to share and spread that same joy to you and your people through both florals for events and floral preservation. We’ll do our best to work with any budget and create a one-of-a-kind floral arrangement to match your person and occasion. We also believe in giving back and getting involved in our community here in San Antonio. So for every bouquet bought we will give another to someone in a local nursing home, assisted living facility, or hospital. Everyone deserves magic moments and by becoming one of our customers, you’ll be helping to spread the magic.'),
(109,'Nicole’s Floral Boutique & Events LLC',3,'At Nicole’s Floral Boutique & Events in San Antonio, we have years of experience to offer you the most stylish and one-of-a-kind designs for your event. We are here to help you design your flowers to fit your occasion of every scale. Floral arrangements, artistic creations, custom creations (floral and non-floral), events of every scale, home, office, venues in and surrounding the San Antonio area.'),
(110,'Eden\'s Echo Floral Design',3,'Welcome to Eden\'s Echo Floral Design & Event Styling! I\'m Erin McLarty, and since 2006 I\'ve been honing my craft and creating bespoke wedding floral designs for incredible couples. My background is in fine art, and I\'m obsessed with nature and beauty, which is reflected in my design. I\'m an artist, a perfectionist, and I love bringing absolute Joy to people via the medium of flowers.'),
(111,'Ay, Poppy Floral & Event Decor',3,'Ay, Poppy! Floral & Event Decor specializes in Event Floral and Decor in San Antonio, Texas. Founded by Cici in 2005, our team is dedicated to creating beautiful and affordable events. Our team specializes in creating beautiful and affordable events that are tailored to your style, preferences, and budget. We understand the stress that wedding planning can bring, and strive to provide clients with supportive and comprehensive wedding planning services that are worry- and hassle-free. We will take care of every detail so that you can enjoy your once-in-a-lifetime wedding experience.'),
(112,'Embellished Event Planning',3,'Hi there! I\'m Norma, owner and stylist behind Embellished. I love all the details and logistics of any and all events. I\'m a certified planner and designer. My attention to detail and immaculate style helps bring your beautiful wedding ideas into real life! Embellished Event planning is a full-service event planning company with a concierge-style of service. From wedding day management to floral design to full planning, we got you covered! \n\nNo two weddings we do are alike because everything we do is custom. Our team of designers will work with you to bring your dream wedding to life. And, we take our jobs seriously! We often work with our couples for 6 months or more so, it\'s important that we build a creative and trusting relationship. We want each of our couples to rest assured that their wedding concept will be everything they dreamed of and more!'),
(113,'De\'s Flowers',3,'De\'s Flowers has been working with couples in South Central Texas since 1999. At De\'s we take pride in our floral designs, and make sure our products are of the best quality for all our clients. We believe that every bride should have confidence in their florist, and with over twenty years of experience, we can guarantee your big day with our high quality services. We absolutely love helping couples live their wedding day dream! \n\nThere\'s no better place to order flowers than with your local San Antonio florist. De\'s Flowers has been built upon generations of florists that have mastered the art of floral design. With sister stores in Piedras Negras and Eagle Pass, anything is possible with us.'),
(114,'Blume Haus Floral Design Studio',3,'Blume Haus - artistically crafting each event with a high level of expertise and creativity. We\'ve been in business since January 2014 and have worked with thousands of happy clients! We can\'t wait to meet you and discuss the vision you have for your event! \n\nOur owner Mandy Blissit, comes from a long and extensive coordinating background. Her deep knowledge of events is carried throughout with Blume Haus does and the deep level it operates. Each team member comes with years of design and execution knowledge and experience and we\'re thrilled to use that knowledge to bring your unique and exquisite event to life through flowers and decor!'),
(115,'The Floral Standard',3,'Originally from Madrid, Spain, Larissa engages the diversity of her travels and love for nature as inspiration for her creations. The Floral Standard is the only business in Texas that creates Specialty Silk Floral Walls. Her walls are available for all occasions and events. Larissa is very particular in her Floral selections. She only uses quality silks from select vendors across the states. Her goal is to create meticulously detailed designs. \n\nFlower Wall Designs created by The Floral Standard. The Floral Standard is the only company in Texas that is exclusive for Flower Walls. We create Fresh Flower Walls, Silk Floral walls and Custom Designs for all of your event needs. Our Walls are always made with single stems which provide a dimensional, intricate aesthetic. We never use mats or panels (which are low quality and often look flat) You deserve quality, this is where you will find it.'),
(116,'The Flower Guy',3,'Local floral artist in San Antonio creating custom weddings and events. Ready to bring your floral visions to life, you imagine and ill create. Allow the floral to speak and make your special day that much more memorable. Planning a wedding can be exhausting, let me help to ease the stress of choosing floras and make it a fun and memorable experience. Keeping budget and theme in mind we will create beautiful floral that will be remembered forever. Whether you\'re planning an extravagant event or intimate ceremony I will be available every step of the way. Message me today for a free consultation.'),
(117,'Chef D’s Catering',4,'Chef D’s Catering prides ourselves with our love for cooking and presentation. Franklin Davis, owner and chef is a cook by trade from years of cooking with his mother. We specialize in full offsite catering, handling everything from open bar to fine dining experience. Creating the perfect friendly environment for a clients, focusing on quality and consistency, giving our clients and customers a memorable experience.'),
(118,'Wild Whisk',4,'We are a private family boutique business working alongside our 4 children to teach them work ethic and business principles. My husband is an attorney and the "meat master” of the operation and I am a former pro makeup artist who now bosses people around about their appetizers and their aesthetic. We attended so many events where the food just sucked…..we knew we could do better and here we are, killing it in catering!!'),
(119,'Honchos - The House of Churros',4,'Say it with Churros! Churros are a traditional Spanish dessert/breakfast, but somehow over the years they have been Latinized; since they are popular in Brazil, Mexico, Peru, Argentina and other Latin American countries. Most people know what Churros are, some of them have tasted and loved them for sure - but for some reason, we couldn\'t find the right experience in popular restaurants or local spots.Wondering with that idea, we set our minds to finding the right ingredients and flavors. Passioned about serving the best churros possible we established our first churro truck on 2016 in San Antonio, Texas.'),
(120,'JC Cooks Catering',4,'JC Cooks is a San Antonio Catering Company and Personal Chef Service. JC Cooks Owner and Chef, Joyce Cunha, is passionate about cooking healthy, mouthwatering dishes for on-the-go, time-strapped people. Joyce brings over 20 years of professional food service experience to the table, and takes pride in preparing and delivering culinary delights that range the gamut from down-home family favorites to international gourmet cuisine. Plus, she is also a pastry chef who enjoys baking her own handmade pies, cakes and holiday cookies.'),
(122,'Frost 321, LLC',4,'After an enchanting wedding in Paris, at roughly 40,000 feet in the air, the idea for Frost 321 was born. Founded by a practicing health attorney, Frost 321 is named to reflect the revolutionary process of freezing at -321 degrees Fahrenheit. Frost 321 creates the best-tasting ice creams, sorbets, and cocktails in the most enchanting way possible. Not only is the taste impeccable, but the experience is unforgettable. Created right before your eyes, Frost 321 provides a dessert experience that excites the taste buds and minds of guests, long after they’ve finished their tasty treats.'),
(123,'Anne Marie’s Catering',4,'Welcome to Anne Marie’s Catering and Banquet Venue. Let us help you plan the perfect event in South Texas. Anne Marie’s at Devonshire Place offers a beautiful Banquet venue which is unsurpassed in design, features and elegance. Worry-free events are what we do best. Let Anne Marie’s Catering hand all the details. From the flowers, décor and everything in between. We make planning your next party easy.'),
(124,'Scratch Kitchen',4,'We are a family-owned bakery, restaurant, and catering company that offers delicious desserts and fine food in San Antonio\'s Alta Vista neighborhood. We are the perfect caterer for brunch weddings, garden weddings, or any wedding where a delicious family-style meal or buffet meal is preferred over a formal sit-down dinner. We also love to cater bridal showers, baby showers, birthday celebrations, and all other parties and meetings! \n\nOwner Becky Medellin serves as the company\'s catering manager, ensuring that couples have her full attention and her eye on all the details. From the menu tasting to the big night, our top priority is delighting the bride and groom!'),
(125,'Four Sisters Catering',4,'You are now experiencing the most exciting and perhaps busiest time of your life...Planning Your Wedding! Four Sisters Catering understands the importance of making your Wedding Day an Affair To Remember. Whether you choose to have an enchanted afternoon event or an evening of splendor, our Wedding Planner specializes in unique, custom wedding packages designed to exceed your every expectation! This will be the first event you will be hosting together as Man & Wife! You want your guests to be impressed! So your every detail is of the utmost importance to US! \n\nFour Sisters Catering is family owned and operated. We have been Catering San Antonio for over 24 years. Our culinary style of gourmet cuisine fused together with our impeccable presentation is our signature and our "family brand." The taste and style of our food is so unique to Four Sisters that we’re 100% confident you will absolutely LOVE it! We have been voted Best Caterers in San Antonio on the Expertise website, 3 years in a row!'),
(126,'Sugar Clouds Cotton Candy',5,'Sugar Clouds makes organic gourmet cotton candy that we spin onsite for all events of any size! We offer 25 delicious flavors! We also package our cotton candy in containers, party cones, beverage glitter bombs, and hot cocoa bombs.We were the first in the area to offer spinning onsite and offer organic and all natural cotton candy. We do not add any food coloring to our sugars so our cotton candy is all white which is so pretty.'),
(127,'Whirls and Swirls Bakery',5,'Superior service and ingredients, personalized attention. We put lots of love and careful thought into all we do. We would love to be a part of your big day, no matter the size of the event! Elopement cake for 2? Dessert Table for 350? 4-tier cake? Dozens of cupcakes? A single dozen cupcakes? Let us celebrate with you! We love to create bold flavor combinations. We have a line of signature flavors, but we are also willing to work with you to make a flavor profile that reflects you and your big (or small) day. Texas Cottage Baker.'),
(128,'Green Cookie Jar',5,'Hello, everyone! This is Ryan Jackson. I am the proud owner of Green Cookie Jar! I make custom cookies! I love traveling, making cookies, and gardening as well! I cannot wait to be able to work with you on your special day!'),
(129,'Meemo\'s Bakery & Cafe',5,'Meemo has been baking custom wedding cakes, wedding cupcakes, and groom’s cakes for over 30 years. Using the finest ingredients like fresh eggs, fresh dairy products, real butter and fresh fruits. We never use mixes or premade fillings. Everything is fresh and delicious. We create stunning wedding cakes to match your personality and wedding theme. Give us a call or email us for a no obligation consultation.'),
(130,'Frost 321, Llc',5,'After an enchanting wedding in Paris, at roughly 40,000 feet in the air, the idea for Frost 321 was born. Founded by a practicing health attorney, Frost 321 is named to reflect the revolutionary process of freezing at -321 degrees Fahrenheit. Frost 321 creates the best-tasting ice creams, sorbets, and cocktails in the most enchanting way possible. Not only is the taste impeccable, but the experience is unforgettable. Created right before your eyes, Frost 321 provides a dessert experience that excites the taste buds and minds of guests, long after they’ve finished their tasty treats.'),
(131,'Jane Dough',5,'Jane dough is a san antonio based cakery that specializes in bespoke cake design and specialty cookies. Jane dough offers custom, traditional, and novelty cakes for any special occasion as well as cookies, cupcakes, and more. It is the mission of jane dough to spread joy in every moment of the day and we encourage all clients to find their joy and choose it everyday, as well. I hope the life you live is filled with all the joy life has to offer and everyday in every moment you choose joy. \n\nJane Dough bakes pure joy into a design specifically curated to embody your unmatched love. Just like your big day, Jane Dough will ensure that your cake is exquisite… and unforgettable. Find out more about our wedding cakes and see the endless possibilities for your big day below!'),
(132,'Sweet Grace',5,'Hi everyone! My name is Malina Lee and I am the owner of Sweet Grace, I run this business with the help of my family. Sweet Grace started out offering just cupcakes but we have grown and our business is now primarily weddings and corporate events. Every single item leaving the Sweet Grace kitchen is not only beautiful and timeless but absolutely delicious. \n\nIn the early days of Sweet Grace I tested and wrote all of the cake recipes still used to this day. At Sweet Grace we pride ourselves on delicious and beautiful products that elevate experience you have on one of those most important days of your life. Thank you for considering Sweet Grace.'),
(133,'Tasty Swirls Company',5,'My name is Desareye and I am the owner of Tasty Swirls Company. I’ve always had a creative side and loved desserts so I wanted to start a business that would combine both. Most importantly share it with you! Cotton Candy has always been a favorite as it is so fluffy, fun and just melts in your mouth making you want more! I wanted our cotton candy to be a little different than your normal pink and blue cotton candy so I decided why not make it with unique flavors. I started to think of what flavors I would do and decided hmm these would taste even better with toppings! We can’t wait to be apart of your event!\n\nTasty Swirls company is known for making the Cotton candy with organic raw cane sugar, natural flavors, and no artificial dyes. We add toppings to our cotton candy which include sprinkles, tajín, sour patch kids, chocolate drizzle and so much more! We have the cart as a blank canvas to help customers design it how they want. Also we can cater to any event whether it be a wedding, baby shower, birthday party, corporate event or public event. I honestly enjoy seeing people of any age get excited when they see their cotton candy getting made and when they take their first bite. Their face just lights up!'),
(134,'Asukar',5,'From show stopping wedding cakes to decadent dessert bars and everything in between, we are here to translate your vision into a both stunning and delicious experience. At Asukar, we push the envelope on how memorable we can make an event by carefully curating the experience down to the sweetest details. \n\nCreating amazing cakes from the ground up truly invigorates me. When I listen to a client\'s story and vision for their special project or event, I am inspired by their ideas. This inspiration is the driving force for me and my team to create something they could have never imagined, but always wanted. What\'s more exciting than that?'),
(135,'Barmasters Texas',6,'BarMasters Texas is a full service bartending and bar planning company based in the San Antonio & Austin areas. We serve at weddings and other special events such as banquets, corporate parties, private events, graduation parties, birthday celebrations, bridal showers, and more. We work closely with you to create the perfect bar for your event! We look forward to the opportunity to serve you at your special event.'),
(136,'Bubble Tap Trailer Co.',6,'Introducing The Bubble Tap Trailer! Established in 2017, we were the first of our kind in the US, The Bubble Tap Trailer brings you Prosecco and Wine straight out of the tap. Our self-contained, vintage 1953 trailer will pull up to your event ready to serve bubbly to you and your guests. Add an element of surprise to your event with The Champagne Room Photo Booth! Located inside the trailer is an adorable lounge with perfect lighting for those AMAZING reception pictures that are sent directly to your phone, and ready for social media!'),
(137,'The Impressed Guest',6,'From small intimate socially-distant parties to weddings for your closest friends and family, we\'re happy to show your guests the top service available. Providing decorated bars based on the theme you choose and exclusive cocktails specifically made to show how you party! ADD SOME FLAIR! Professional flair bartenders will blow your audience away with a show they won\'t soon forget.'),
(138,'MMK Mixology Services LLC',6,'Our talented team brings years of hospitality experience and unmatched enthusiasm to every private event. We understand just how much time and effort goes into planning a wedding or special event and provide each client with service that consistently exceeds expectations. From the initial consultation to cleanup, we will be with you every step of the way to assist with every last detail.'),
(139,'D&J\'s Margaritas, Music & More',6,'We are a wedding bar and beverages service based in Victoria, TX. Our charming bar trailer is just what you need to take your wedding celebration to the next level. Our goal is to make your event stress-free and fun! We can also provide a karaoke stage complete with a Bluetooth-compatible sound system, microphones, and lights. You and your guests can sing and dance the night away. We also have a state-of-the-art photo booth so that you can capture memories you\'ll cherish forever. Your wedding is an opportunity to share extraordinary experiences with family and friends, and we can\'t wait to help you celebrate in style. \n\nD&J\'s Margaritas, Music & More aims to not only bring the fun but also help your special day be as stress-free as possible. By offering our mobile bar trailer and bartending service, as well as the options for the karaoke stage and sound system, as well as the photo booth, we want to be your one-stop-shop to help make things as easy as possible.'),
(140,'Rocking R & B',6,'Rocking R & B offers unique party rentals to the Texas Hill Country. We currently have a two horse trailer that we renovated into a mobile bar. It is equipped with a cooler room that can fit 4 full size kegs, liquor dispensers that hold up to six bottles and room to serve. \n\nWe have one of the few mobile bars that has a climate controlled keg room with a tap system that can serve four varieties at a time. We also are capable of serving beer, wine and liquor all at the same time with a unique rustic look.'),
(141,'Tap Truck Usa',6,'Tap Truck provides cocktail and beverage catering for locations across the U.S. and International. Most people recognize us as a draft beer truck but we also offer wine, cocktail bar catering, and non-alcoholic options. We service events ranging from 25 to 5,000 thirsty guests. Our portable bar rental services events such as: weddings, private parties, corporate events, beer festivals, football game tailgates and much more! Tap Truck USA is the premier mobile bar experience for any and all occasions serving whatever beverages your guests desire. \n\nTap Truck USA is the original vintage beer truck and mobile bar experience. The four pillars or building blocks of Tap Truck⁠ are exceptional service, accountability and integrity⁠, uniqueness and flexibility⁠, and of course a refined beverage palate. We take the stress out of your events and handle all your bars needs.'),
(142,'Barista Kats',6,'Let us help you create memorable events your guests will not forget. Our Baristas are creative, attentive, engaging and they love nothing more than delivering delicious pours, espressos, signature lattes and more. Whether you\'re hosting a business conference, convention, meeting, special event, wedding and more, you\'ll get a customized Coffee Bar complete with Barista serving some of the world\'s best coffees!\n\nWe provide excellent service and specialize in catering craft coffees. We have Coffee Mobile Bars and talented Baristas. Bringing this service to your convention, meeting, wedding and events of all sizes.'),
(143,'Bring It! Productions',7,'Bring It Productions takes pride in delivering each and every time. A DJ can make or break your wedding day- we understand that and believe in giving a bride exactly what she wants. This is YOUR big day and you deserve it to be as magical as you have always dreamed it to be. We have any and all styles of music and cater that to what you want but we are way more than just an individual playing music. We are entertainment, We are MC’s, We also offer Karaoke, rentals and lighting! While you are at it, do not forget to ask us about our Photo booths. Take advantage of our free consultation and remember. You Dream It… We Bring IT!!! \n\nThe willingness to go the extra mile to make sure your event is as perfect as possible. We work with all aspects of the wedding and all other vendors so we can magically make every moment the most special of the night.'),
(144,'Dj Masquerade And Photo Booths',7,'LIFE IS BETTER WHEN YOU DANCE! Masquerade DJ & Photo Booths is your Best choice for your Dream Wedding and Exciting Birthday Party or Reunion or any occasion to celebrate! You can select the music from over 200,000 songs in every category from top hits.'),
(145,'ICADJ Events',7,'One of the most frequently asked questions is, "What music do you play?" Well, since music is digital everyone can now claim to be a DJ. The difference is the experience of when to play it, how long to play the song, and listening to what the client is asking for. During your consultation, we will help you create your custom playlist. Some of our past clients prefer full control and request we only play what\'s on the list of songs requested. Just think, what do I want for my event? How can I make my dreams come to reality?'),
(146,'Everjoy Entertainment',7,'To ensure a seamless, stress-free experience, Everjoy Entertainment offers unlimited consultations, allowing you to meet with us as many times as you like. Our packages includes four to six hours of music, event setup and teardown, and two fun event extras of your choice. We provide live instrumental guitar, piano, or cello music which adds a nice live musical component to the atmosphere. You may also opt to enhance your package with a range of á-la-carte add-ons, cold sparklers, customized monogram, among others. For an unforgettable night of entertainment, contact Everjoy Entertainment today!'),
(147,'Finding Friday',7,'Finding Friday is a polished, high energy cover band based out of San Antonio. Playing hits from the 70’s – today, Finding Friday takes pride in keeping the audience entertained and the dance floor jam-packed. With superstar lead vocalist, Christopher Byrd, leading the way, the group covers some of the most vocally gifted artists out there such as Journey, Bruno Mars and Earth Wind & Fire to name a few. Finding Friday also features female vocalists, Jennifer Espinoza and Jazmin Lopez, who deliver stunning lead and background vocal performances.'),
(148,'Carlos Sanchez',7,'Carlos Sanchez is an Award Winning Guitarist, Rated #1 in the San Antonio and surrounding areas. Carlos performs as a Solo Guitarist, Spanish Guitar Duo, Trio or 4 piece Band. For almost any kind of event, Carlos will add that special touch you are looking for. He is an expert at setting the perfect ambience for your event. One of the greatest compliments from his clients is his vast repertoire which includes music form many genres across time. His Clients love his professionalism and how he treats you as if you were his only client. His attention to detail and perfectionist attitude will allow you to relax and focus on other things. \n\nCarlos has a Master’s Degree in Classical Guitar performance and has received master instruction through great musicians from Spain, Cuba, Chile, US, Mexico, among others and has been performing for more than 30 years. Carlos knows the importance of professionalism and timeliness. He meets with couples to discuss their desires for the wedding, and then is sure to arrive on time and prepared when the day comes. He will guide you through the entire process from the first call to the day of. Carlos will provide music for not only the ceremony, but also your cocktail hour, reception, and rehearsal dinner. Carlos is willing to travel Nationwide.'),
(149,'DJMusic Entertainment LLC',7,'At DJMusic Entertainment, we bring our client\'s vision to life with an Exceptional and Unique, Entertainment and Wedding Planning Experience. Our main goal and passion are to go beyond our clients’ expectations. We believe that small details can make a big difference. \n\nWe are passionate about weddings, our team is always an extraordinary duo of DJ and Timeline Assistant who will make sure the Ceremony and Reception run smooth and on time. We help our brides with educational materials.'),
(150,'At Last Entertainment',7,'At Last Entertainment has a decade of experience doing events – weddings are our specialty. We are very detail oriented in the planning and execution of an event. We bring the fun and the energy to your guests and bring the calm and confidence to our couple. Contact us today to learn more!'),
(151,'iDJ Events',7,'iDJ Events is committed to make sure that all of your events are special and that your guests have a great time. Be ready to sing along to your favorite songs and dance all night when you hire iDJ Events in San Antonio or Austin TX. Our well-dressed and articulated DJs and MCs strive to be professional and amazing. \n\nWe bring our client\'s vision to life with an exceptional and unique, entertainment experience. We are DJ\'s dedicated to helping every bride and groom feel important and special on their big day. Our main goal and passion are to go beyond our client\'s expectations. We are DJ\'s working solely to meet your needs and ensure your dreams come true.'),
(152,'Starlite Entertainment Management & Productions',7,'Percussion dynamo Henry Brun, has performed on more than 845 recordings, including numerous Grammy-winning and gold / platinum-award winning albums. Brun’s dedication to musical excellence has earned him the opportunity to tour and record with such artists as Arturo Sandoval, Justo Almario, Nestor Torres, Charo, Los Lobos, Texas Tornados, Little Joe y La Familia and Los Super Seven. His passion for music lead him to launch Starlite Entertainment, a company that prides itself in representing the highest level of talent in San Antonio. Most of their members are award winning artists of national or international status.\n\nDon’t be scared! Our philosophy is render top notch entertainment at a reasonable cost. We understand what it takes to make an event happen and its cost. We also are cognizant of budgetary limitations, so why not try and let us do our magic for you? We can customize any entertainment package to fit your budget! Don’t sacrifice quality because of budget. Ask before you decide. I’m sure you will be pleased with what we can do within your budget.');

select id, user_id from vendors;

#Add Vendor's Services Provided
INSERT INTO `vendor_services` (`vendor_id`, `title`) VALUES
(46,'Bride-only session'),
(46,'Engagement session'),
(46,'Extra hours'),
(46,'Image editing'),
(46,'Online proofing'),
(46,'Printing rights'),
(46,'Same-day edits'),
(46,'Second photographer'),
(70,'Consultations and tastings - for a fee'),
(70,'Delivery and setup'),
(70,'Breakfast/brunch'),
(70,'Buffet'),
(70,'Dessert service'),
(70,'Family-style meal'),
(70,'Food stations'),
(70,'Stationary appetizers'),
(71,'Rental coordination - directly invoice couple'),
(71,'Rental coordination - does not invoice couple'),
(63,'A La Carte'),
(63,'Full-Service Floral Design'),
(63,'Consultations'),
(63,'Mock-ups'),
(63,'Venue visits'),
(63,'Cleanup'),
(63,'Container rentals'),
(63,'Decor rentals'),
(63,'Delivery'),
(63,'Setup'),
(63,'Structure rentals'),
(63,'Architectural with branches and twigs'),
(63,'Flower-forward with fresh blooms'),
(63,'Foliage-centric with leaves and tall grasses'),
(63,'Bouquets'),
(63,'Boutonnieres'),
(63,'Cake flowers'),
(63,'Centerpieces'),
(63,'Ceremony decor'),
(63,'Flower baskets'),
(63,'Flower crowns'),
(63,'Flower jewelry'),
(63,'Installations'),
(63,'Table runners'),
(76,'Cleanup and breakdown'),
(76,'Consultations and tastings - complimentary'),
(76,'Delivery and setup'),
(76,'Rental coordination - directly invoice couple'),
(76,'Serving staff'),
(76,'Dessert service'),
(76,'Mixers/non-alcoholic options'),
(76,'Mobile bar'),
(76,'Signature cocktails'),
(76,'Cookies and macarons'),
(76,'Cupcakes'),
(76,'Donuts'),
(76,'Mini desserts'),
(76,'Novelties and other'),
(76,'Cake toppers'),
(76,'Custom text'),
(76,'Fruit topping'),
(76,'Live flowers'),
(76,'Sugar flowers'),
(76,'Cake toppers'),
(76,'Custom text'),
(76,'Fruit topping'),
(76,'Live flowers'),
(76,'Sugar flowers'),
(76,'Cake toppers'),
(76,'Custom text'),
(76,'Fruit topping'),
(76,'Live flowers'),
(76,'Sugar flowers'),
(78,'Cakes'),
(78,'Cookies and macarons'),
(78,'Cupcakes'),
(78,'Mini desserts'),
(78,'Novelties and other'),
(78,'Cake toppers'),
(78,'Custom text'),
(78,'Fruit topping'),
(78,'Live flowers'),
(78,'Sugar flowers'),
(78,'Cake filling'),
(78,'Cake flavors'),
(78,'Cake frosting'),
(78,'Cake filling'),
(78,'Cake flavors'),
(78,'Cake frosting'),
(79,'Candy and confections'),
(79,'Novelties and other'),
(79,'Consultations'),
(79,'Delivery'),
(79,'Setup'),
(79,'Tastings'),
(80,'Cakes'),
(80,'Cookies and macarons'),
(80,'Cupcakes'),
(80,'Donuts'),
(80,'Ice cream and frozen desserts'),
(80,'Mini desserts'),
(80,'Pies'),
(80,'Novelties and other'),
(80,'Consultations'),
(80,'Delivery'),
(80,'Setup'),
(80,'Tastings'),
(85,'Bartenders'),
(85,'Cleanup and breakdown'),
(85,'Consultations and tastings - complimentary'),
(85,'Delivery and setup'),
(85,'Event planner'),
(85,'Beverage servingware rentals'),
(85,'Mixers/non-alcoholic options'),
(85,'Mobile bar'),
(86,'Mobile bar'),
(87,'Rental coordination - directly invoice couple'),
(88,'Bartenders'),
(88,'Delivery and setup'),
(89,'Band Backdrop'),
(89,'Ceremony microphones and sound'),
(89,'Dancefloor lighting'),
(89,'Fog/Snow machines'),
(89,'Learning new songs'),
(89,'Master of ceremonies'),
(89,'Multiple location support'),
(89,'Music during breaks'),
(89,'Photobooth'),
(89,'Sound system capability audience <300 -'),
(89,'Sound system capability audience >300'),
(89,'Uplighting'),
(94,'Ceremony microphones and sound'),
(94,'Learning new songs'),
(94,'Multiple location support'),
(94,'Music during breaks'),
(94,'Sound system capability audience <300 -'),
(94,'Sound system capability audience >300'),
(95,'Ceremony microphones and sound'),
(95,'Dance floor special effects'),
(95,'Dancefloor lighting'),
(95,'Event planning'),
(95,'Fog/Snow machines'),
(95,'Master of ceremonies'),
(95,'Multimedia displays'),
(95,'Multiple location support'),
(95,'Music during breaks'),
(95,'Photobooth'),
(95,'Projector equipment'),
(95,'Signs'),
(95,'Sound system capability audience <300 -'),
(95,'Sound system capability audience >300'),
(95,'Sparklers'),
(95,'Stage design'),
(95,'Uplighting'),
(96,'Band Backdrop'),
(96,'Ceremony microphones and sound'),
(96,'Confetti'),
(96,'Dance floor'),
(96,'Dance floor special effects'),
(96,'Dancefloor lighting'),
(96,'Event planning'),
(96,'Fog/Snow machines'),
(96,'Learning new songs'),
(96,'Master of ceremonies'),
(96,'Multiple location support'),
(96,'Music during breaks'),
(96,'Photobooth'),
(96,'Projector equipment'),
(96,'Signs'),
(96,'Sound system capability audience <300 -'),
(96,'Sound system capability audience >300'),
(96,'Sparklers'),
(96,'Uplighting'),
(97,'Ceremony microphones and sound'),
(97,'Dance floor special effects'),
(97,'Dancefloor lighting'),
(97,'Event planning'),
(97,'Master of ceremonies'),
(97,'Photobooth'),
(97,'Sound system capability audience <300 -'),
(97,'Sound system capability audience >300'),
(97,'Uplighting'),
(98,'Ceremony microphones and sound'),
(98,'Confetti'),
(98,'Event planning'),
(98,'Fog/Snow machines'),
(98,'Hear us live'),
(98,'Master of ceremonies'),
(98,'Multiple location support'),
(98,'Music during breaks'),
(98,'Photobooth'),
(98,'Projector equipment'),
(98,'Sound system capability audience <300 -'),
(98,'Sound system capability audience >300'),
(98,'Sparklers'),
(98,'Uplighting');

#Add Vendor Packages if applicable
INSERT INTO `vendor_packages` (`title`, `description`, `vendor_id`) VALUES
('All inclusive','With this all inclusive package, you can literally just \'enjoy the ride\'! This package includes: Engagement Session with 2 outfits Bridal/Rehearsal Dinner Full wedding day coverage',46),
('Simple and Sweet','With this Simple and Sweet package you will receive: A sunset engagement session 6 hours of wedding day coverage *This packaged can be customized to your needs',46),
('Elopement Package','Elopement full coverage',46),
('Intimate','1 Hour Live Spun Cotton Candy Service with Unlimited Servings • 3-4 Flavors • Toppings Included!',79),
('Social','2 Hour Live Spun Cotton Candy Service with Unlimited Servings • 3-4 Flavors • Toppings Included!',79),
('Grand','3 Hour Live Spun Cotton Candy Service with Unlimited Servings • 3-4 Flavors • Toppings Included!',79),
('Ceremony Package','This Complete Ceremony Package contains all the features for a beautiful wedding service. Your ceremony starts with background music of your choice and style to set the perfect romantic mood as your guests take their seats. The duties of our DJ & Event Expert include the correct timing of music being played as your wedding party walks in and constant monitoring of the microphone to prevent annoying feedback.',95),
('Silver Package','Our \"Silver Reception Package\" contains all the features for a great celebration! It starts with cocktail and dinner music of your choice to set the perfect mood for your reception. Our DJ will perform the duties of Master of Ceremony, including introductions, toasts, and other formalities you wish to include, it will also perfectly mix your favorite dance tunes & motivate your guests.',95),
('Gold Package','This \"Gold Reception Package\" has the same features as our Silver Package plus one Enhancement.',95),
('Platinum Package','Our \"Platinum Reception Package\" has the same features as our Gold Package but it includes two enhancements.',95),
('Diamond Package','Our \"Diamond Reception Package\" has the same features as our Platinum Package but it includes 2 hours of our Photo Booth',95),
('Enhancements','You can pick between one or two enhancements depending of you wedding package',95),
('Bokeh Elopement Microwedding Photography','The Bokeh Photography package is perfect for an elopement or micro-wedding. Planned accordingly we can possibly squeeze in time for photos getting ready or an intimate shoot post ceremony. You will receive 100-150 photos.',51),
('Copper Wedding Photography Package','The Copper Photography package is our most popular photo package. Most of our 2020-21 weddings have been around the 6-8 hour time frame. You will receive 400-500 photos with 100 highly edited portraits. (We don\t charge by number of guests, which we think is better for our customers)',51),
('Copper & Birch Film//Photography Package','The Copper & Birch package has been our most popular this year. Most of our 2020-21 weddings have been around the 6-8 hour time frame. First off, we book you for a FREE engagement OR Bridal shoot. The sooner the better on this so you can create all your invitations and social posts. You will receive a 6-7 minute wedding film using live audio and video to tell your love story and 400-500 photos with 100 highly edited portraits.',51),
('Champagne Wedding Photography Package','The Champagne Photography package is for larger weddings that last a little longer. You will receive 600 - 800 photos including 150 highly edited portraits. We will be there to capture you getting ready all the way to the moment you leave on your new journey.',51),
('Rose Gold & Champagne Film/Photo Package','The Rose Gold & Champagne Film & Photography is for larger weddings that last a little longer. First off, we book you for a FREE engagement or Bridal shoot. (The sooner the better on this so you can create all your invitations and social posts) You will receive a 7 - 9 minute wedding film using live audio and video to tell your love story. You will also receive 3 Wedding Reel/Tik Tok videos and 600-800 photos with 150 highly edited portraits.',51),
('Birch Wedding Film Package','The Birch film package is our most popular package. Most of our 2020-21 weddings have been around the 6-8 hour time frame. You will receive a 6-7 minute wedding film using live audio and video to tell your love story.',51),
('Rose Gold Wedding Film Package','The Rose Gold Film packages for larger weddings that last a little longer. You will receive a 7 - 9 minute wedding film using live audio and video to tell your love story. You will also receive 3 Wedding Reel/Tik Tok videos',51),
('Wedding Shoutout Video','Have a special section with lighting and microphones to give your guests an opportunity to share testimonies, marriage advice, fun or emotional stories, kind words, or just a nice congratulations. All your shoutouts are organized and cut into a final video. If you have booked us for your wedding film we create a cute intro with special shots from your wedding. (We try to use mostly shots here that are not in the final wedding film so we can get you nice and teary eyed again)',51);


insert into djs_and_live_bands (vendor_id, dalb_category_id) values
(89, 1),
(90, 1),
(91, 1),
(92, 1),
(93, 3),
(94, 4),
(95, 1),
(96, 1),
(97, 1),
(98, 2);

select * from djs_and_live_bands;

insert into djs_and_live_bands_music_genres (dj_or_live_band_id, music_genre_id) values
(6,8),
(6,6),
(6,6),
(6,9),
(6,12),
(6,4),
(6,1),
(6,3),
(6,7),
(6,13),
(6,18),
(6,16),
(11,8),
(11,9),
(11,12),
(11,1),
(11,18),
(11,19),
(13,20),
(13,21),
(13,16),
(13,8),
(13,6),
(13,15),
(13,15),
(13,9),
(13,12),
(13,4),
(13,1),
(13,3),
(13,7),
(13,13),
(13,18),
(13,8),
(14,6),
(14,15),
(14,12),
(14,4),
(14,1),
(14,3),
(14,7),
(14,18),
(14,20),
(15,8),
(15,6),
(15,6),
(15,9),
(15,12),
(15,4),
(15,1),
(15,3),
(15,7),
(15,13),
(15,18),
(15,18);

#duplicate business names
select *
from (select v.business_name, v.id as vendor_id, v.user_id from vendors v
      where business_name in (select business_name from vendors group by business_name having count(*) > 1)
     ) as v
join users u on u.id = v.user_id
order by business_name, vendor_id;

# add vendor photo format
insert into vendors_photo_format (vendor_id, photo_format_id) values
(46,1),
(47,1),
(48,1),
(49,3),
(50,3),
(51,1),
(52,3),
(53,3);

select * from users u
join customers c on u.id = c.user_id;

INSERT INTO `users` (`email`, `username`, `password`, `first_name`, `last_name`, `city`, `state`) VALUES
('kelly.lambert@email.com', 'kelly.lambert@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Kelly', 'Lambert', 'San Antonio', 'TX'),
('annie.mccarty@email.com', 'annie.mccarty@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Annie', 'McCarty', 'San Antonio', 'TX'),
('sherrie.leblanc@email.com', 'sherrie.leblanc@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Sherrie', 'Leblanc', 'San Antonio', 'TX'),
('beatriz.maxwell@email.com', 'beatriz.maxwell@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Beatriz', 'Maxwell', 'San Antonio', 'TX'),
('april.osborne@email.com', 'april.osborne@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'April', 'Osborne', 'San Antonio', 'TX'),
('holly.wheeler@email.com', 'holly.wheeler@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Holly', 'Wheeler', 'San Antonio', 'TX'),
('meghan.beck@email.com', 'meghan.beck@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Meghan', 'Beck', 'San Antonio', 'TX'),
('marion.morse@email.com', 'marion.morse@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Marion', 'Morse', 'San Antonio', 'TX'),
('jocelyn.cook@email.com', 'jocelyn.cook@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jocelyn', 'Cook', 'San Antonio', 'TX'),
('rachael.callahan@email.com', 'rachael.callahan@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Rachael', 'Callahan', 'San Antonio', 'TX'),
('jasmine.williamson@email.com', 'jasmine.williamson@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jasmine', 'Williamson', 'San Antonio', 'TX'),
('irene.short@email.com', 'irene.short@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Irene', 'Short', 'San Antonio', 'TX'),
('shari.crawford@email.com', 'shari.crawford@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Shari', 'Crawford', 'San Antonio', 'TX'),
('janelle.larson@email.com', 'janelle.larson@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Janelle', 'Larson', 'San Antonio', 'TX'),
('tamara.king@email.com', 'tamara.king@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Tamara', 'King', 'San Antonio', 'TX'),
('jane.hansen@email.com', 'jane.hansen@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jane', 'Hansen', 'San Antonio', 'TX'),
('stefanie.coon@email.com', 'stefanie.coon@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Stefanie', 'Coon', 'San Antonio', 'TX'),
('patty.shay@email.com', 'patty.shay@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Patty', 'Shay', 'San Antonio', 'TX'),
('violet.moody@email.com', 'violet.moody@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Violet', 'Moody', 'San Antonio', 'TX'),
('hilda.spence@email.com', 'hilda.spence@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Hilda', 'Spence', 'San Antonio', 'TX'),
('kathy.mckee@email.com', 'kathy.mckee@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Kathy', 'McKee', 'San Antonio', 'TX'),
('wanda.pitts@email.com', 'wanda.pitts@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Wanda', 'Pitts', 'San Antonio', 'TX'),
('yvonne.washburn@email.com', 'yvonne.washburn@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Yvonne', 'Washburn', 'San Antonio', 'TX'),
('nadine.goldstein@email.com', 'nadine.goldstein@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Nadine', 'Goldstein', 'San Antonio', 'TX'),
('alison.petty@email.com', 'alison.petty@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Alison', 'Petty', 'San Antonio', 'TX'),
('jeanette.cramer@email.com', 'jeanette.cramer@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Jeanette', 'Cramer', 'San Antonio', 'TX'),
('celeste.gay@email.com', 'celeste.gay@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Celeste', 'Gay', 'San Antonio', 'TX'),
('eileen.myers@email.com', 'eileen.myers@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Eileen', 'Myers', 'San Antonio', 'TX'),
('lindsay.costello@email.com', 'lindsay.costello@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Lindsay', 'Costello', 'San Antonio', 'TX'),
('guadalupe.lowery@email.com', 'guadalupe.lowery@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Guadalupe', 'Lowery', 'San Antonio', 'TX'),
('molly.mayer@email.com', 'molly.mayer@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Molly', 'Mayer', 'San Antonio', 'TX'),
('emma.burch@email.com', 'emma.burch@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Emma', 'Burch', 'San Antonio', 'TX'),
('erin.dillon@email.com', 'erin.dillon@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Erin', 'Dillon', 'San Antonio', 'TX'),
('mabel.strong@email.com', 'mabel.strong@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Mabel', 'Strong', 'San Antonio', 'TX'),
('diane.massey@email.com', 'diane.massey@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Diane', 'Massey', 'San Antonio', 'TX'),
('miriam.waller@email.com', 'miriam.waller@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Miriam', 'Waller', 'San Antonio', 'TX'),
('aimee.hayes@email.com', 'aimee.hayes@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Aimee', 'Hayes', 'San Antonio', 'TX'),
('myrtle.bonner@email.com', 'myrtle.bonner@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Myrtle', 'Bonner', 'San Antonio', 'TX'),
('norma.swan@email.com', 'norma.swan@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Norma', 'Swan', 'San Antonio', 'TX'),
('kristie.frederick@email.com', 'kristie.frederick@email.com', '$2a$10$GYNeIa.HSIqhpGA3tYfuxefGKJ1gCckwTyQAGXjaTs4WBjl3NKlGu', 'Kristie', 'Frederick', 'San Antonio', 'TX');

INSERT INTO `user_groups` (`user_id`, `group_id`)
SELECT u.id, 2
from users u
left join user_groups g on u.id = g.user_id
where g.user_id is null;

#customers who are not in the customer table yet
select u.username, u.id
from users u
join user_groups g on
u.id = g.user_id
left join customers c on u.id = c.user_id
where g.group_id = 2 and c.user_id is null;

#MIN: 14309, MAX: 23848
insert into customers (budget, guest_count, partner_fname, partner_lname, user_id, wedding_dt) values
(19799, 148, 'Hubert', 'Wheeler', 153, '2023-11-12'),
(15667, 117, 'Arthur', 'King', 154, '2024-02-08'),
(19674, 147, 'Lorenzo', 'Drake', 155, '2024-03-29'),
(15567, 116, 'Wesley', 'Bullock', 156, '2023-12-31'),
(23034, 172, 'Craig', 'Wu', 157, '2023-10-11'),
(21681, 162, 'Andre', 'Hayden', 158, '2024-03-19'),
(21313, 159, 'Jen', 'Vaughn', 159, '2024-01-12'),
(20596, 154, 'Leon', 'Armstrong', 160, '2023-12-01'),
(14449, 108, 'Abraham', 'Park', 161, '2024-01-04'),
(19120, 143, 'Bruce', 'Sweeney', 162, '2024-03-31'),
(15080, 113, 'Harold', 'Meyer', 163, '2023-09-20'),
(18845, 141, 'Jan', 'Curry', 164, '2024-02-13'),
(14731, 110, 'Gregg', 'Johnson', 165, '2023-09-06'),
(22342, 167, 'Ruben', 'Bradley', 166, '2023-09-01'),
(23068, 173, 'Anthony', 'Singh', 167, '2023-10-08'),
(22894, 171, 'Arnold', 'Bass', 168, '2023-10-20'),
(16415, 123, 'Jimmy', 'McDonald', 169, '2023-11-01'),
(14692, 110, 'Travis', 'Cantrell', 170, '2023-11-22'),
(18856, 141, 'Francis', 'Copeland', 171, '2024-02-19'),
(20061, 150, 'Cliff', 'Davidson', 172, '2024-03-27'),
(21472, 161, 'Frankie', 'Clements', 173, '2023-12-19'),
(23766, 178, 'Greg', 'Sparks', 174, '2023-12-30'),
(14600, 109, 'Will', 'Travis', 175, '2023-10-02'),
(21342, 160, 'Curtis', 'Witt', 176, '2024-01-23'),
(17657, 132, 'Paul', 'Meyers', 177, '2024-01-01'),
(18297, 137, 'Thomas', 'Dixon', 178, '2023-12-08'),
(21104, 158, 'Randolph', 'Rodgers', 179, '2024-04-26'),
(19095, 143, 'Al', 'Villarreal', 180, '2023-11-17'),
(21934, 164, 'Matt', 'Anderson', 181, '2024-03-26'),
(23168, 173, 'Emmanuel', 'McMillan', 182, '2023-11-15'),
(23625, 177, 'Mike', 'Preston', 183, '2023-12-27'),
(14685, 110, 'Christopher', 'Figueroa', 184, '2023-12-01'),
(20184, 151, 'Aaron', 'McGill', 185, '2023-09-14'),
(23402, 175, 'Damon', 'Bower', 186, '2024-02-23'),
(21082, 158, 'Preston', 'Cooley', 187, '2023-12-13'),
(18794, 140, 'Stanley', 'Bennett', 188, '2024-03-06'),
(19315, 144, 'Roderick', 'Rowe', 189, '2024-04-19'),
(14683, 110, 'Gerry', 'Roberts', 190, '2024-01-21'),
(16036, 120, 'Jeffrey', 'Daily', 191, '2023-09-24'),
(18330, 137, 'Dwayne', 'Goodwin', 192, '2024-03-13');

# insert vendor reviews
insert into vendor_ratings_reviews (title, description, rating, vendor_id, customer_id) values
('110% amazing','Karen was very kind and have all of the information regarding the venue and options. She answered any/all questions very quickly. I’d do it all over again! Such a gorgeous venue and at a great price. We had our wedding on a Sunday.',5,40,30),
('Really thought I\'d love but let down.','was overall happy with the wedding because of course it\'s supposed to be a joyous event. However I would be reluctant to refer them to a friend. The coordinator we were assigned to left the company a several months out from the wedding. We were assured that the new person taking over would take care of our needs. Flat out the ball was dropped. The coordination from that point was a disaster. We were never given a tasting even though it was built into the price. I asked multiple times. We finally were asked to come to the venue for another walk through to plan where things would go for both ceremony and reception and we would have a tasting at that meeting. Gave our availability. No response. Reached out again the next week with more availability and then they got back to us. Did not have a tasting. After that I was reaching out for over a week maybe 2 by phone and email about how many tables etc so that decor could adequately be planned. No response. I then started just contacting the venue and not the coordinator directly and was passed to someone else that said they would be taking over from there. I was then basically called and asked everything we were asked when we had last met with the coordinator at the venue (where we were wanting things etc). Clearly that meeting was pointless. This call was literally weeks before the wedding. Wedding day came and their venue set up workers were not on time and would not let my coordinator and helpers set up do to liability since their people WEREN\'T THERE YET. This was all going on while I was getting ready off site so I was in the dark until I got there. There may have been other mishaps I\'m forgetting during that set up but again I was not there. Of course I wasn\'t 100% happy with the food. UGH. Most of it was great however if we had a tasting I definitely would\'ve axed 2 of the items. Specifically the chicken and waffles. Waffle was eggo quality. We booked a year out so this can not be an issue of time.',2,41,31),
('Look no further!','Cassia is the best! She goes above and beyond what you could ask for. She gets to know you and what you are wanting as well as giving wonderful recommendations when you ask for them. Very accommodating to your requests and professional. Cassia has been the photographer for my wedding, my sisters wedding, and family event photos. Highly recommend!',5,46,32),
('Mr.','John was great to communicate with, very flexible and accommodating. He had set poses in mind but was also open to us doing different things.',5,47,33),
('Excellent service','We’re so glad we hired John G photography LLC as our photographer. John was punctual, organized, friendly, and overall made us feel very comfortable. My husband and I are not very photogenic, but John made sure he could capture us at our most natural state. We wanted someone who specialized in sunset photography since our wedding was later in the day. If you’re looking for someone who can capture those sunset pictures look no further. One thing I especially loved about John’s photography is not only does he capture those candid photos, but he’s also great at coaching you to get the best poses possible. John is very talented and will most definitely make your dream pictures come true.',5,47,34),
('Made our day','Our greatest hope for our wedding was for everything to be personal and authentic to us as a couple and John\'s presence that day/professionalism was a big part of that being possible. John was extremely flexible for two very go with the flow, figure it out when we get there people. Planning an OOT wedding at a private residence, John was great with communication and making sure we were all on the same page for the day of. John was a genuine, kind presence to have at our wedding and we would\'ve loved that energy in general, but he ALSO caught all of these sweet moments from our dearest memory.',5,47,40),
('Amazing Photographer!','John G Photography made the photo sessions such an enjoyable experience! During the actual ceremony I never even noticed he was there, but the photos say otherwise! Absolutely perfect! He made everything feel so natural and captured it in such a way that I feel the emotions all over again every time I view the photos.',5,47,41),
('Hire her!!','I cannot speak highly enough of Aliyah and her colleague Amani!! They were punctual, professional and friendly, they made us all feel so comfortable which is so important in photographers. My fear was feeling awkward and coming out stiff in the photos especially considering I‚Äôm not used to having all eyes on me and multiple cameras. But from the moment they arrived all those fears went away! They were amazing, the photos were beautiful. Aliyah got all of the photos on my shot list and photos I never knew I wanted!! Absolutely adore her and would recommend and hire again. You will not regret going with Aliyah!',5,52,1),
('Aliyah is the best!','Aliyah photographed our engagement shoot and wedding in the summer of 2022. Her photos are absolutely beautiful and we love them so much!! We are truly overwhelmed by all the special moments that she captured. We were also so impressed with her turnaround time on sharing the photos, which were super easy to view and download via her online platform. But most importantly, we had so much fun working with her (and her assistant, Amani! Shout-out to Amani)! Aliyah is great to be around and made us feel totally comfortable. After our engagement shoot, it felt like she was an old friend by the time of the wedding and we were genuinely so happy to have her there. One of the best pieces of wedding advice that we have is to get a photographer that you think will mesh well with your friends and family, put you at ease with all the intense emotions of the day, and bring fun and positive energy to the party. Aliyah is all those things and more, and she has our highest recommendation.',5,52,11),
('Love, love this team','They are easy to work with. Making every couple feel so comfortable. They really ensure that you get the best pictures possible. Highly recommend.',5,48,12),
('Feels like friends, instead of strangers!','Ashley and Tyler are the best! We met them over the summer and did our engagement shoot with them and absolutely fell in love with their work. Ashley was also sooooo helpful in helping to make our timeline for photos. When it came to our wedding day Ashley and Tyler were right on time and made sure we got the best shots. I got some sneak peaks back on Monday night and I am absolutely in love with them and can\'t wait to get the rest back!',5,48,13),
('Communication is On Point!!','A photographer was a huge priority in my wedding planning process! It was also the hardest for me to find! I found Ashley & Tyler on a facebook group and instantly fell in love with their website!! I almost went the route of having a friend take my photos until I read their personal story! it was literally like I was supposed to find them!! I reached out and got a reply within hours!! Ashley is the sweetest human and we facetimed for over an hour just talking about wedding stuff and how my fianc√© and I met! it was literally like being on the phone with a friend!!! she has been amazing during all the planning and planned our engagement/family session!! she was so helpful with picking out outfits since i‚Äôm so indecisive! her personality is so fun!! she really turned our awkwardness into beautiful pictures. i am looking forward for our big day coming up in april! honestly i‚Äôm more excited for it to fly by just so I can see all the awesome pictures they take!!! knowing I picked the perfect photographer just eases my stress about the big day!!‚Äô her and tyler are seriously amazing!!! I have no doubt my fianc√© and I will counting on our friendship with Ashley and Tyler after our special day!!!',4,48,14),
('Personable & Fun!!','We took a chance on hiring Ashley and Tyler to capture the pictures for our engagement wedding photos. Since the time we met on Zoom, we knew working with them would be great! They made us feel comfortable and answered all of our questions. Fast forward to the time of our engagement session and we found out we weren‚Äôt going to be able to use the property in our original plans but Ashley reassured us that everything would workout and helped find a new location. We loved our engagement pictures! Ashley was also great about keeping in contact throughout the time leading up to the wedding and also helped with making a timeline. On our wedding day, she and Tyler were awesome. They got straight to work on capturing our special day and making everyone feel comfortable. I would definitely recommend them for any event and we will definitely plan on using them in the future.',5,48,15),
('Amazing - they made our day','We HIGHLY recommend CiCi & Imelda to help with your wedding! They were an amazing and dedicated team as they focused on the important details for our special day. We were very fortunate and blessed that our paths crossed. We had originally reached out for a floral arrangement quote early June, and to our relief, CiCi & Imelda had a response in the inbox the next day. It was a great sign for us and our short, 3-month engagement. They included in their quote a very reasonable offer for additional services: a day of coordinator. The Bride had always wanted a day of coordinator, but thought it wasn‚Äôt in the cards. The Groom was confused by the concept and was immediately against the idea. He is now one of CiCi and Imelda‚Äôs biggest fans and more than willing to admit he lived to eat his words, with, ‚Äúfind CiCi‚Äù becoming a reliable response on our big day! As for the Bride, she felt like she had a team to work with, not just organizing the wedding day itself, but also executing her dream. She had always wanted a fairytale wedding and was afraid to allow herself to hope for one. She had to admit it was everything she envisioned and more ‚Äì so much of that was due to their efforts. Our wedding went off smoothly and without a hitch, all because of Ay, Poppy Floral and Event D√©cor. Thank you ladies, truly!',5,58,16),
('Cosmic Cakery','Beautiful floral arrangements! I have worked with Ay Poppy many times with floral arrangements for cakes. I highly recommend them for any of your floral needs!',5,58,17),
('Ay Poppy Floral & Event Decor','We loved working with Ay Poppy for one of our brides weddings. The floral was beautiful. The team was so easy to work with and accommodating! The bride was very happy! We hope to work future events with them.',5,58,18),
('BarMasters is AMAZING!!!','We absolutely LOVED working with BarMasters TX! They were very professional, fun to work with, and Jenna was very knowledgable and helpful with everything. It felt good to know that we didn\'t have to worry about anything and knew our guests would have a great time. Cannot recommend BarMasters enough!',5,81,19),
('BarMasters TX more than just bartending','I\'ve been in the wedding industry for many years now and Jenna with BarMasters TX provides a truly excellent service from start to finish. She is easy to communicate with, friendly, and knows her stuff when it comes to planning and serving your event. I have always enjoyed working with BarMasters TX and I value their professionalism.',5,81,25),
('Amazing!!','Easy to work with and the flowers exceeded our expectations on wedding day!',5,61,26),
('Assistant Director of Student Engagement - TAMUC','First, Bubble Tap is so much fun! Dawn created a safe and fun environment for our campus. Would highly recommend.',5,82,27),
('HIGHLY Recommend','Dawn and her team are amazing!! I would highly recommend!! She is professional, on time, and makes the events so much fun!',5,82,30),
('Truly the best','If you want a VIP experience hire Dawn & The Bubble Tap! Will absolutely separate your event from the rest - we love working with her!',5,82,31),
('Cannot Recommend Enough!!!','Bubble Tap is AMAZING!! We rented the trailer for our rehearsal dinner and it was a big hit! We had so much fun, everyone was amazed champagne came from a tap! And the Champagne Room photo booth is a MUST! I cannot express how much fun it was trying to all pile into the trailer for pictures. Dawn was amazing, beyond perfect! The communication was top notch and she made sure everything went off without a hitch! I‚Äôm making events just so I can rent this again! You will not be disappointed!!',5,82,32),
('Best Catering Ever','Oh my gosh the food is delicious! Chef D‚Äôs Catering is one of the best company‚Äôs I have had the pleasure of working with. Frank is so professional, easy to work with, and he caters to every guest. It‚Äôs very impressive how he is able to curate unique experiences for different guests each time. I love working with him!',5,64,33),
('Wow! Thank you!','Working with Dawn with D&J\'s Margaritas was a great experience. She made every step of the process easy and fun. Our guests had a great time at the wedding and we didn\'t have to worry about a thing. Would definitely recommend them to our friends and family and use them again in the future.',5,85,34),
('A Pleasure to Work With','I have worked with Dawn at D&J\'s Margaritas, Music & More several times and she has always been a pleasure to work with. She conducts herself professionally and communicates her needs well. Looking forward to working with Dawn again in the future.',5,85,40),
('An amazingly talented and skilled photographer!','David is truly a professional in his field and extremely talented at his craft and you can tell how passionate he is about what he does. He has an eye for detail - his photos really stand out, from the composition to the lighting. When you work with David, you will see that he has great patience, is very kind and flexible. You won\'t feel rushed through your photos and he really takes his time to get the perfect shot - every time! As a bridal makeup artist I really enjoy working with David any chance I get because I know everything will turn out great. I really can\'t say enough about how professional David is and the quality of work that he provides, and I cannot recommend him enough to everyone!',5,50,41),
('Gorgeous Work, Great Team!','I had the privilege of working with the De\'s Flowers team on a luxury-inspired photoshoot at a wedding venue in Fredericksburg. The product was fresh and beautifully designed, and the team was able to set up and tear down in a timely manner. Those ladies are as professional as they come, so definitely get a quote for your event before they run out of availability! 10/10 would work together with De\'s Flowers again!!',5,60,1),
('Happy Couple','The day ran so smoothly. We were able to enjoy town with our families and be present at our wedding.',5,59,11),
('Maternity photos','Evelyn took the time to coordinate with me and we both planned my maternity photos. She made my husband and I feel comfortable and cared for. He\'s a bit shy but she was able to get him put of his shell. Great photographer!',5,53,12),
('Best Photographer EVER','We love working with Idea House! All the photographers are so nice and every picture comes out so amazing! I normally look so bad on camera but somehow they make me look great! I‚Äôll 100% be using them again! Can‚Äôt wait till the next time I need pictures taken!',5,51,13),
('Amazing videography!','Idea house media really made our wedding video perfect! They captured the true beauty from the beginning to the end of our special day. The shots were very cinematic and told the perfect love story. We put so much planning and effort into our wedding and Idea house media had it all covered with extensive , high end equipment and hard working , passionate videographers who care about capturing a once in a lifetime event. We highly recommend!',5,51,14),
('Beautiful and Magical Wedding Video','Idea House Media went above and beyond with our wedding video! They captured the best moments of the night and we‚Äôre very detailed with our video! They include so much creativity and hard work to each piece they create. They are great and fun people to work with. We couldn‚Äôt have ask for a better videographer! We‚Äôve been married for over four years, and every time we watch our wedding video, we relive the moment all over again! We are so thankful for the entire Idea House team that made our wedding very special and one to always remember!',5,51,15),
('Amazing Photography!!! Instagram Worthy Pictures!!','My husband and I have used Idea House Media several times for couples photos which is why it was an easy choice for us to choose them to photograph our elopement/mini wedding. They were super professional and took amazing photos that my husband and I love! Everything is sent nice and organized in a folder we can access at any time. We continue to use them whenever we want updated couple/family pictures. There is consistency in the quality of their work and every photo they have taken of us is always Instagram-worthy! 10/10 highly recommend',5,51,16),
('Party Planner','Wonderful experience, great service and very knowledgeable.',5,84,17),
('Extremely Professional and Sharply Dressed','I highly recommend MMK Mixology Services for anyone planning a special event or occasion. We used them for our wedding reception and our expectations were beyond exceeded. They were sharply dressed and very professional, giving our wedding that extra touch of class and elegance. The drinks were the best, very creative, and properly garnished to look as good as they tasted. We couldn\'t have asked for more. Thank you MMK Mixology for making our wedding a memorable one!',5,84,18),
('Saved my bar at my wedding','MMK was a huge lifesaver when it came to the bar at my wedding. I had no clue what I was doing and Kealie came in and helped me figure out what to serve and how much to get for my reception. Her team was extremely outgoing and kind to all of my guests and not one person had anything negative to say about the bar. I would give 10 stars if I could because without bringing in MMK, the bar at my wedding would have been a complete disaster.',5,84,19),
('Great to work with','Working with Kealie and the MMK Team never ceases to amaze me. With the professionalism she has and the quality of customer service her and her team provide, I never turn down the opportunity to work with them. They have the best ideas for the bar that they allow my team to bring to life and their clients are never disappointed.',5,84,25),
('Extremely helpful','Was super nervous about my bar at my wedding but MMK came in right away to help ease my mind. They were extremely helpful with figuring out how much alcohol to get for the wedding, and what kinds of alcohol. Easiest process ever. I‚Äôll be using them for other events for sure.',5,84,26),
('Goes beyond all expectations','Working with MMK Mixology and their team made my life so much easier when it came to getting the bar together for my daughter\'s wedding. We were so stressed out and Kealie came in and was able to help me calculate how much alcohol to buy for all the guests almost perfectly. The little extra touches she gives to the bar area are super cute and her team is outgoing and kept the party going all night. She also was able to help me go over the entire wedding plan to make sure we didn\'t miss anything, and I am sure glad we did. I will be using her and her team again for my birthday party in a couple of months. I would give 10 stars if I could!',5,84,27),
('Wedding','The owners had a fast response and answered all questions asked. So easy to work with when renting. They went above and beyond to rent even though they were going out of town. I highly recommend them. We had so many compliments on the bar and how cool it looked.',5,86,30),
('Awesome mobile bar!','Rocking R&B provided an amazing mobile bar at our ranch wedding venue. We are adding them to our preferred vendor list for all of our weddings and events.',5,86,31),
('Absolutely Amazing Brunch Catering','My wife Sarah and I wanted to try something a tad unorthodox to celebrate our wedding: a brunch reception. We hoped to find a great, local brunch caterer, and we discovered Scratch Kitchen. The 3 other catering companies we tried in San Antonio tasted like the bland, frozen cafeteria food you\'d find in a middle school. We were floored by every dish at Scratch Kitchen, and were surprised such fresh, homemade food could be shared with 160 guests! We got only compliments at our reception about the food, and we have only compliments for Becky and her team\'s communication, professionalism, and food quality. If you want a great brunch served to your guests or coworkers, look no further!',5,70,32),
('Bride','INCREDIBLE caterer. The food was spectacular and had both families still talking about how good it was. Super easy to work with and quick to communicate. Excellent selection of food and treat options. Gave us all the details and information we needed super quickly. Set up and take down were so breezy. Scratch Kitchen was the perfect addition to our wedding.',5,70,33),
('Exceedingly Exceptional!!','I am recommending The Floral Standard for countless reasons. Here are a few of my must haves: 1. The ease and simplistic interaction, not overbearing! 2. Professionalism 3. Selection and availability 4. Understanding my vision and taking it to the next level! Totally exceeding expectations. 5. Personal service. Making me feel like I am the most important person in the room! This is The Floral Standard because I only recommend excellence!',5,62,34),
('Grace and Excellence!','I‚Äôve seen flower walls before BUT I‚Äôve never seen flower walls like this! The detailed work is impeccable and mind blowing. I love them.',5,62,40),
('High Standards All Around','The Floral Standard offers the Most gorgeous, non-cookie cutter, high-quality silk/artificial floral walls I\'ve ever seen in my 15 years of floral design. Larissa is very passionate, loves what she does, has so much energy, and is very kind. On top of that, The Floral Standard is very professional, and thorough when it comes to scheduling and executing events. I would highly recommend this company to anyone wanting a gorgeous backdrop for their event!',5,62,41),
('SUPERB and HIGHLY RECOMMENDED','The flower walls are so beautiful that they can be used for all Ocassions. I give this company an triple A rating and that the creator for her professionalism and care.',5,62,1);